/**
 * Write each published app into its own folder for easy self-hosting.
 * Local: generated-apps/{slug}/
 * Vercel: also mirrored to Blob under verlin-labs/generated-apps/{slug}/
 */
import { put } from "@vercel/blob";
import fs from "fs";
import path from "path";
import type { AppProject, EcomLocalShopContent } from "@/lib/app-builder/types";
import { buildStaticSiteFiles } from "@/lib/app-builder/static-export";

const GENERATED_ROOT = "generated-apps";
const BLOB_PREFIX = "verlin-labs/generated-apps/";

function isVercelRuntime(): boolean {
  return process.env.VERCEL === "1" || Boolean(process.env.VERCEL_ENV);
}

function isBlobEnabled(): boolean {
  return Boolean(process.env.BLOB_READ_WRITE_TOKEN);
}

function appDir(slug: string): string {
  // On Vercel, write under /tmp so the package exists for the request lifecycle
  const root = isVercelRuntime()
    ? path.join("/tmp", "verlin-labs-generated-apps")
    : path.join(process.cwd(), GENERATED_ROOT);
  return path.join(root, slug);
}

export function getGeneratedAppDir(slug: string): string {
  return appDir(slug);
}

function writeLocalFiles(slug: string, files: Record<string, string>): string {
  const dir = appDir(slug);
  fs.mkdirSync(dir, { recursive: true });
  fs.mkdirSync(path.join(dir, "site"), { recursive: true });

  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, "utf8");
  }
  return dir;
}

async function mirrorToBlob(slug: string, files: Record<string, string>): Promise<void> {
  if (!isBlobEnabled()) return;
  await Promise.all(
    Object.entries(files).map(async ([rel, content]) => {
      const key = `${BLOB_PREFIX}${slug}/${rel.replace(/\\/g, "/")}`;
      await put(key, content, {
        access: "private",
        addRandomSuffix: false,
        allowOverwrite: true,
        contentType: rel.endsWith(".html")
          ? "text/html; charset=utf-8"
          : rel.endsWith(".json")
            ? "application/json"
            : "text/plain; charset=utf-8",
      });
    })
  );
}

function readmeFor(project: AppProject): string {
  return `# ${project.name}

This folder was generated by **Verlin Labs App Builder**.

## What's inside

| File | Purpose |
|------|---------|
| \`project.json\` | Full shop data (products, colours, contact) |
| \`site/index.html\` | Complete website - open in a browser or upload to any host |
| \`README.md\` | This file |

## Host anywhere (no coding)

1. Open the \`site\` folder.
2. Upload **all files inside \`site\`** to any static host:
   - Netlify Drop
   - Cloudflare Pages
   - GitHub Pages
   - Hostinger / GoDaddy file manager
   - Or just open \`index.html\` on your computer
3. Share the public link with customers.

## Live on Verlin Labs

While published, your shop is also available at:

\`${project.publicPath}\`

on the Verlin Labs website.

## Do not edit

- API keys are never stored here.
- Safe to zip and email this folder to a developer or host.

Generated: ${new Date().toISOString()}
Slug: \`${project.slug}\`
Extension: \`${project.extensionId}\`
`;
}

/**
 * Persist a per-app folder (local disk + Blob) after generate/publish.
 */
export async function packageAppProject(project: AppProject): Promise<{
  folderPath: string;
  files: string[];
}> {
  if (!project.content || project.extensionId !== "ecom-local-shop") {
    throw new Error("Only live ecom-local-shop apps can be packaged");
  }

  const content = project.content as EcomLocalShopContent;
  const siteFiles = buildStaticSiteFiles(content, project.slug);
  const files: Record<string, string> = {
    "project.json": JSON.stringify(project, null, 2) + "\n",
    "README.md": readmeFor(project),
    ...Object.fromEntries(
      Object.entries(siteFiles).map(([name, body]) => [`site/${name}`, body])
    ),
  };

  const folderPath = writeLocalFiles(project.slug, files);

  try {
    await mirrorToBlob(project.slug, files);
  } catch (error) {
    console.error("[app-builder] Blob mirror of generated app failed:", error);
  }

  return {
    folderPath,
    files: Object.keys(files),
  };
}

export async function removePackagedApp(slug: string): Promise<void> {
  const dir = appDir(slug);
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
  // Blob leftovers are overwritten on next publish; skip delete API for simplicity
}

/** Read packaged files from disk for download API */
export function readPackagedFiles(slug: string): Record<string, string> | null {
  const dir = appDir(slug);
  if (!fs.existsSync(dir)) return null;

  const out: Record<string, string> = {};
  const walk = (base: string, prefix = "") => {
    for (const name of fs.readdirSync(base)) {
      const full = path.join(base, name);
      const rel = prefix ? `${prefix}/${name}` : name;
      if (fs.statSync(full).isDirectory()) walk(full, rel);
      else out[rel] = fs.readFileSync(full, "utf8");
    }
  };
  walk(dir);
  return out;
}
